import os
import time
import requests
import cv2
from typing import Callable
from urllib.parse import quote
from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt
from intelli.core.brain import HybridBrain

class GenerationHandlers:
    def __init__(
        self,
        speak: Callable[[str], None],
        brain: HybridBrain,
    ):
        self.speak = speak
        self.brain = brain
        self.output_dir = os.path.join(os.getcwd(), "generated_media")
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def handle_image_generation(self, query: str) -> bool:
        self.speak("Generating image. Please wait.")
        try:
            prompt = self.brain.generate_image_prompt(query)
            if not prompt:
                prompt = query
            safe_prompt = quote(prompt)
            url = f"https://image.pollinations.ai/prompt/{safe_prompt}"
            
            response = requests.get(url, timeout=30)
            if response.status_code == 200:
                filename = f"image_{int(time.time())}.jpg"
                filepath = os.path.join(self.output_dir, filename)
                with open(filepath, 'wb') as f:
                    f.write(response.content)
                self.speak(f"Image generated and saved as {filename}")
            else:
                self.speak("Failed to generate image from server.")
        except Exception as e:
            print(f"Image generation error: {e}")
            self.speak("Sorry, I encountered an error while generating the image.")
        return True

    def handle_docx_generation(self, query: str) -> bool:
        self.speak("Drafting a massive, professional document. This might take a minute.")
        try:
            topic = query.lower().replace("generate document", "").replace("create doc", "").replace("write a report", "").strip()
            if not topic:
                topic = "General Subject"
            
            prompt = (
                f"Write a highly comprehensive, multi-page professional report about: {topic}. "
                "Include a deep introduction, 3-5 major sections with detailed professional analysis, "
                "bulleted lists where appropriate, and a strong conclusion. Make it extremely long and detailed."
            )
            content = self.brain.generate_response(prompt)
            
            doc = Document()
            doc.add_heading(f"Comprehensive Report: {topic.title()}", 0)
            
            # Simple Markdown-ish parsing
            for line in content.split('\n'):
                line = line.strip()
                if not line:
                    continue
                if line.startswith('#'):
                    # Heading
                    level = line.count('#')
                    clean_text = line.replace('#', '').strip()
                    # Limit heading level since docx max is 9
                    doc.add_heading(clean_text, min(level, 4))
                elif line.startswith('- ') or line.startswith('* '):
                    doc.add_paragraph(line[2:], style='List Bullet')
                elif len(line) > 2 and line[0].isdigit() and line[1:3] in ['. ', ') ']:
                    doc.add_paragraph(line[3:], style='List Number')
                else:
                    doc.add_paragraph(line)
            
            filename = f"Document_{int(time.time())}.docx"
            filepath = os.path.join(self.output_dir, filename)
            doc.save(filepath)
            self.speak(f"Pro-level document created successfully and saved as {filename}")
        except Exception as e:
            print(f"Docx error: {e}")
            self.speak("Sorry, there was an issue creating the document.")
        return True

    def handle_pptx_generation(self, query: str) -> bool:
        self.speak("Building a massive presentation. Please wait.")
        try:
            topic = query.lower().replace("generate presentation", "").replace("create ppt", "").replace("make slides", "").strip()
            if not topic:
                topic = "Presentation"
                
            prompt = (
                f"Create a highly detailed 10-15 slide presentation outline for: {topic}. "
                "Format EXACTLY as follows for each slide:\n"
                "Slide X: [Title]\n"
                "- [Bullet point 1]\n"
                "- [Bullet point 2]\n"
                "- [Bullet point 3]"
            )
            outline = self.brain.generate_response(prompt)
            
            prs = Presentation()
            # Title slide
            title_slide = prs.slides.add_slide(prs.slide_layouts[0])
            title_slide.shapes.title.text = topic.title()
            title_slide.placeholders[1].text = "Generated by INTELLI AI"
            
            current_slide = None
            text_frame = None
            
            for line in outline.split('\n'):
                line = line.strip()
                if not line:
                    continue
                if line.lower().startswith("slide") and ":" in line:
                    # New slide
                    slide_layout = prs.slide_layouts[1] # Title and Content
                    current_slide = prs.slides.add_slide(slide_layout)
                    parts = line.split(":", 1)
                    current_slide.shapes.title.text = parts[1].strip()
                    text_frame = current_slide.placeholders[1].text_frame
                    text_frame.text = ""  # clearing default
                elif (line.startswith('-') or line.startswith('*')) and current_slide and text_frame:
                    p = text_frame.add_paragraph()
                    p.text = line[1:].strip()
            
            filename = f"Presentation_{int(time.time())}.pptx"
            filepath = os.path.join(self.output_dir, filename)
            prs.save(filepath)
            self.speak(f"Pro-level presentation finished and saved as {filename}")
        except Exception as e:
            print(f"PPTX error: {e}")
            self.speak("Failed to create the presentation.")
        return True

    def handle_video_generation(self, query: str) -> bool:
        self.speak("Generating a short AI video sequence. Please wait.")
        try:
            prompt = self.brain.generate_image_prompt(query)
            if not prompt:
                prompt = query
            
            # Generate 3 images for a basic slideshow video
            images = []
            for i in range(3):
                safe_prompt = quote(f"{prompt} scene {i+1}")
                url = f"https://image.pollinations.ai/prompt/{safe_prompt}"
                resp = requests.get(url, timeout=30)
                if resp.status_code == 200:
                    img_path = os.path.join(self.output_dir, f"temp_frame_{i}.jpg")
                    with open(img_path, 'wb') as f:
                        f.write(resp.content)
                    images.append(img_path)
                    
            if not images:
                self.speak("Failed to generate video frames.")
                return True
                
            # Stitch with CV2
            first_frame = cv2.imread(images[0])
            height, width, layers = first_frame.shape
            
            vid_filename = f"Video_{int(time.time())}.avi"
            vid_filepath = os.path.join(self.output_dir, vid_filename)
            video = cv2.VideoWriter(vid_filepath, cv2.VideoWriter_fourcc(*"XVID"), 1, (width, height))
            
            for img_path in images:
                frame = cv2.imread(img_path)
                # write each frame 3 times to make the video longer (3 seconds per image)
                video.write(frame)
                video.write(frame)
                video.write(frame)
                
            video.release()
            
            # cleanup temp images
            for img_path in images:
                if os.path.exists(img_path):
                    os.remove(img_path)
                    
            self.speak(f"Video sequence created and saved as {vid_filename}")
            
        except Exception as e:
            print(f"Video error: {e}")
            self.speak("Failed to create the video string.")
        return True
